<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-26T03:26:51 IST" name="Suite" finished-at="2022-02-26T03:29:48 IST" duration-ms="177163">
    <groups>
    </groups>
    <test started-at="2022-02-26T03:26:51 IST" name="TwoTest" finished-at="2022-02-26T03:28:14 IST" duration-ms="82673">
      <class name="tests.TwoTest">
        <test-method signature="testTwo()[pri:0, instance:tests.TwoTest@48e1f6c7]" started-at="2022-02-26T03:26:51 IST" name="testTwo" finished-at="2022-02-26T03:28:14 IST" duration-ms="82240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
      </class> <!-- tests.TwoTest -->
    </test> <!-- TwoTest -->
    <test started-at="2022-02-26T03:26:51 IST" name="FourTest" finished-at="2022-02-26T03:28:18 IST" duration-ms="86802">
      <class name="tests.FourTest">
        <test-method signature="testFour()[pri:0, instance:tests.FourTest@268f106e]" started-at="2022-02-26T03:26:51 IST" name="testFour" finished-at="2022-02-26T03:28:14 IST" duration-ms="82504" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.FourTest.testFour(FourTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFour -->
      </class> <!-- tests.FourTest -->
    </test> <!-- FourTest -->
    <test started-at="2022-02-26T03:26:51 IST" name="ThreeTest" finished-at="2022-02-26T03:28:14 IST" duration-ms="82661">
      <class name="tests.ThreeTest">
        <test-method signature="testThree()[pri:0, instance:tests.ThreeTest@6f15d60e]" started-at="2022-02-26T03:26:51 IST" name="testThree" finished-at="2022-02-26T03:28:14 IST" duration-ms="82242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
      </class> <!-- tests.ThreeTest -->
    </test> <!-- ThreeTest -->
    <test started-at="2022-02-26T03:26:51 IST" name="LoginTest" finished-at="2022-02-26T03:29:48 IST" duration-ms="177163">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:tests.LoginTest@60f00693]" started-at="2022-02-26T03:26:51 IST" name="openApplication" finished-at="2022-02-26T03:28:14 IST" duration-ms="82239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@60f00693]" started-at="2022-02-26T03:28:14 IST" name="login" data-provider="getLoginData" finished-at="2022-02-26T03:28:31 IST" duration-ms="16976" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[sonie_selenium@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[soni1234]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Successfull]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closure()[pri:0, instance:tests.LoginTest@60f00693]" started-at="2022-02-26T03:28:31 IST" name="closure" finished-at="2022-02-26T03:28:31 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
        <test-method is-config="true" signature="openApplication()[pri:0, instance:tests.LoginTest@60f00693]" started-at="2022-02-26T03:28:31 IST" name="openApplication" finished-at="2022-02-26T03:29:34 IST" duration-ms="63504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@60f00693]" started-at="2022-02-26T03:29:34 IST" name="login" data-provider="getLoginData" finished-at="2022-02-26T03:29:48 IST" duration-ms="14348" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[dummy@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Failure]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closure()[pri:0, instance:tests.LoginTest@60f00693]" started-at="2022-02-26T03:29:48 IST" name="closure" finished-at="2022-02-26T03:29:48 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- Suite -->
</testng-results>
